### ISSUE TITLE
Crash when using query "INSERT"

### ISSUE THREAD

**Issue by christoffersch** [Malkverbena/MySQL_Module#2]
It seems that when using this module and using the `"INSERT"` query, the application will crash with no error thrown. Data will successfully be sent to the database, however.

I tried to reproduce this bug many, many times, but cannot find the reason behind it.
The only pattern I noticed was that the longer my code was, the less the chance for the query to work (the query works fine on a new, empty project).

Finally, I exported my project and ran it on the command line to see what error I would get.
Here it is:

https://gist.github.com/christoffersch/0c519c830a2445b5fa3d3bb5c7d146aa

Hope you can make something out of this, since this is the only MySQL connector for Godot that connects to online databases right now :-)

**Comment by Malkverbena** [comment]
Sorry for take so long to answer.
I'm aware about it. 
The problem is on line 69 of mysql.cpp
Should be "res = stmt->executeQuery(SQLquery);"  insted "stmt->execute(SQLquery);"
But I can't change anything from now. Even answer this was very difficult due my bad connection in this moment.
Anyway, don't use this code> I wrote this very sleep and did't notice the problems. (which a many).
As soon I back to shore I'll upload a better code.

**Comment by Malkverbena** [comment]
I did several changes on  the module. This issue are solved. If you find any other problem, please, let me know.
